// Run locally before deployment. The sources and this generator never deploy.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const model = require('./content-model.cjs');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const check = process.argv.includes('--check');
function output(file, text) {
    if (check) assert.equal(read(file).replace(/\r\n/g, '\n'), text.replace(/\r\n/g, '\n'), `Stale generated output: ${file}`);
    else fs.writeFileSync(path.join(root, file), text);
}
const published = model.getPublishedArticles();
assert.equal(new Set(published.map(a => a.id)).size, published.length);
const escape = model.escapeArticleText;
const template = read('.editorial/article-template.html');
const origin = 'https://www.tv96live.org';
const imageManifest = JSON.parse(read('.editorial/optimized-images.json'));
const deliveryImage = article => article.image === '/editorial-fallback.png' ? article.image : article.image ? article.image.replace(/\.png$/i, '.webp') : '';
const marker = '<!-- Generated by .editorial/generate-static.cjs; edit the central sources. -->';
if (!check) fs.mkdirSync(path.join(root, 'articles'), { recursive: true });
for (const article of published) {
    assert(Number.isSafeInteger(article.id) && article.id > 0);
    const url = `${origin}/articles/${article.id}`;
    const title = `${article.title} | TV96 Live`;
    const delivered = deliveryImage(article);
    if (delivered && delivered !== '/editorial-fallback.png') {
        const record = imageManifest[article.image];
        assert(record, `Unoptimized image: ${article.image}`);
        for (const [asset, expected] of [[article.image, record.sourceSha256], [delivered, record.deliverySha256]]) {
            assert(fs.existsSync(path.join(root, asset.slice(1))), `Missing image: ${asset}`);
            assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root, asset.slice(1)))).digest('hex'), expected, `Stale optimized asset: ${asset}`);
        }
    }
    const image = new URL(delivered || '/editorial-fallback.png', origin).href;
    const schema = {
        '@context': 'https://schema.org', '@type': 'Article', headline: article.title,
        description: article.description, mainEntityOfPage: url, url,
        datePublished: article.publishedAt, articleSection: article.category,
        author: { '@type': 'Organization', name: article.author },
        publisher: { '@type': 'Organization', name: 'TV96 Live' },
        wordCount: article.wordCount, inLanguage: 'en'
    };
    if (article.updatedAt) schema.dateModified = article.updatedAt;
    if (article.image) schema.image = image;
    const head = `<title id="page-title">${escape(title)}</title>
    <meta id="meta-description" name="description" content="${escape(article.description)}">
    <link id="canonical-url" rel="canonical" href="${url}">
    <meta id="og-title" property="og:title" content="${escape(title)}">
    <meta id="og-description" property="og:description" content="${escape(article.description)}">
    <meta id="og-url" property="og:url" content="${url}">
    <meta property="og:type" content="article">
    <meta id="og-image" property="og:image" content="${escape(image)}">
    <meta property="article:published_time" content="${escape(article.publishedAt)}">
    <meta property="article:modified_time" content="${escape(article.updatedAt || article.publishedAt)}">
    <meta property="article:author" content="${escape(article.author)}">
    <script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script>`;
    const date = value => new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(value));
    const fields = {
        HEAD: head, TITLE: escape(article.title), PUBLISHED: escape(article.publishedAt), DATE: date(article.publishedAt),
        UPDATED: article.updatedAt ? ` · Updated <time datetime="${escape(article.updatedAt)}">${date(article.updatedAt)}</time>` : '',
        CATEGORY: escape(article.category), AUTHOR: escape(article.author), TYPE: escape(`${article.articleType} · ${model.getArticleReadingTime(article)}`),
        IMAGE: delivered ? `<img class="article-main-image" src="${escape(delivered)}" alt="${escape(article.imageAlt || article.title)}" decoding="async">\n        ` : '',
        BODY: model.articleContent[article.id],
        SOURCES: (article.sources || []).map(source => `<a href="${escape(source.url)}" target="_blank" rel="noopener noreferrer">${escape(source.name)}</a>`).join('; '),
        RELATED: model.getRelatedArticles(article).map(model.renderArticleSummary).join('\n')
    };
    output(`articles/${article.id}.html`, template.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + marker).replace(/\{\{([A-Z]+)\}\}/g, (_, key) => {
        assert(Object.hasOwn(fields, key), `Unknown template field: ${key}`);
        return fields[key];
    }));
}
// Unpublishing removes only files made by this generator, never unrelated files.
for (const name of fs.readdirSync(path.join(root, 'articles'))) {
    if (!/^\d+\.html$/.test(name) || published.some(a => name === `${a.id}.html`)) continue;
    assert(read(`articles/${name}`).includes(marker), `Refusing to remove non-generated file: ${name}`);
    assert(!check, `Stale unpublished page: ${name}`);
    fs.unlinkSync(path.join(root, 'articles', name));
}
output('news-data.js', '// Generated published-only metadata. Edit .editorial/news-data.js and regenerate.\nconst articles = ' + JSON.stringify(published.map(({ imageCandidate, imageReviewRequired, sourceReviewRequired, imageType, rightsStatus, brandingReview, ...publicRecord }) => ({ ...publicRecord, image: deliveryImage(publicRecord) })), null, 4) + ';\n\n' + model.helpers.map(name => model[name].toString()).join('\n\n') + '\n');
let news = read('news.html');
for (const [name, value] of Object.entries({ FEATURED: model.getFeaturedArticles(3).map(model.renderArticleSummary).join('\n'), NEWS: [...published].sort((a,b) => new Date(b.publishedAt) - new Date(a.publishedAt) || b.id - a.id).map(a => model.renderNewsCard({ ...a, image: deliveryImage(a) })).join('\n'), COUNT: `${published.length} articles · All` })) {
    const pattern = new RegExp(`(<!-- BEGIN STATIC ${name} -->)[\\s\\S]*?(<!-- END STATIC ${name} -->)`);
    assert(pattern.test(news), `Missing News marker: ${name}`);
    news = news.replace(pattern, (_, start, end) => start + value + end);
}
output('news.html', news);
const home = read('index.html');
const homeMarker = /(<!-- BEGIN STATIC HOME -->)[\s\S]*?(<!-- END STATIC HOME -->)/;
assert(homeMarker.test(home), 'Missing homepage Featured marker');
output('index.html', home.replace(homeMarker, (_, start, end) => start + model.renderHomeFeatured(model.getHomeArticles().map(a => ({ ...a, image: deliveryImage(a) }))).replace(/[\t ]+$/gm, '') + end));
const streamingEnabled = /const STREAMING_ENABLED\s*=\s*true/.test(read('site-config.js'));
output('watch-live.html', read('watch-live.html').replace(/(<!-- BEGIN STREAMING INDEXING -->)[\s\S]*?(<!-- END STREAMING INDEXING -->)/, (_, start, end) => start + (streamingEnabled ? '' : '<meta name="robots" content="noindex, follow">') + end));
const pages = ['', 'matches', 'standings', 'news', 'about', 'contact', 'privacy', 'terms'];
const urls = pages.map(page => `  <url><loc>${origin}/${page}</loc></url>`);
for (const a of published) urls.push(`  <url><loc>${origin}/articles/${a.id}</loc><lastmod>${(a.updatedAt || a.publishedAt).slice(0,10)}</lastmod></url>`);
output('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls.join('\n') + '\n</urlset>\n');
const config = JSON.parse(read('vercel.json'));
config.rewrites = (config.rewrites || []).filter(rule => rule.source !== '/articles/:id');
if (!config.rewrites.length) delete config.rewrites;
const retirements = require('./article-retirements.cjs');
const mergedRoutes = Object.keys(retirements.merged).map(id => `/articles/${id}`);
config.redirects = config.redirects.filter(rule => rule.source !== '/article-template' && !mergedRoutes.includes(rule.source));
config.redirects.push(...published.map(a => ({ source: '/article-template', has: [{ type: 'query', key: 'id', value: String(a.id) }], destination: `/articles/${a.id}`, permanent: true })));
for (const [id, destination] of Object.entries(retirements.merged)) {
    assert(published.some(a => a.id === destination), `Unpublished merge destination: ${destination}`);
    config.redirects.push({ source: `/articles/${id}`, destination: `/articles/${destination}`, permanent: true });
    config.redirects.push({ source: '/article-template', has: [{ type: 'query', key: 'id', value: id }], destination: `/articles/${destination}`, permanent: true });
}
output('vercel.json', JSON.stringify(config, null, 2) + '\n');
console.log(`PASS: ${published.length} static articles ${check ? 'verified' : 'generated'}, published-only metadata, raw News discovery, sitemap and legacy redirects.`);
